spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: devP@ss
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    com.madhax: debug

server:
  port: 8901

token:
  access:
    timeout: 300
  refresh:
    timeout: 600
