spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: devP@ss
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.madhax: debug

server:
  servlet:
    context-path: /auth
  port: 8901
