spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/authdb"
    username: "postgres"
    password: "devP@ss"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
token:
  access:
    timeout: 300
  refresh:
    timeout: 600
